### ISSUE TITLE
Permission Issues w/ install

### ISSUE THREAD

**Issue by 1092MousePad39** [dgreif/homebridge-ring-alarm#10]
I'm getting consistent permission issues when trying to install.  I have homebridge running fine and I've installed other plugins without issue.  Relevant part of debug.log below.

I even tried:
` sudo npm install -g homebridge-ring-alarm --unsafe-perm=true --allow-root`
But still getting errors.  I also had this confirmed by another user with another Pi who has homebridge and other plugins working fine.

192 silly install generateActionsToTake
193 warn checkPermissions Missing write access to /usr/lib/node_modules
194 timing stage:rollbackFailedOptional Completed in 2ms
195 timing stage:runTopLevelLifecycles Completed in 5580ms
196 verbose stack Error: EACCES: permission denied, access '/usr/lib/node_modules'
197 verbose cwd /home/pi
198 verbose Linux 4.14.79-v7+
199 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "homebridge-ring-alarm"
200 verbose node v8.15.0
201 verbose npm  v6.6.0-next.1
202 error path /usr/lib/node_modules
203 error code EACCES
204 error errno -13
205 error syscall access
206 error Error: EACCES: permission denied, access '/usr/lib/node_modules'
206 error  { Error: EACCES: permission denied, access '/usr/lib/node_modules'
206 error   stack: 'Error: EACCES: permission denied, access \'/usr/lib/node_modules\'',
206 error   errno: -13,
206 error   code: 'EACCES',
206 error   syscall: 'access',
206 error   path: '/usr/lib/node_modules' }
207 error The operation was rejected by your operating system.
207 error It is likely you do not have the permissions to access this file as the current user
207 error
207 error If you believe this might be a permissions issue, please double-check the
207 error permissions of the file and its containing directories, or try running
207 error the command again as root/Administrator (though this is not recommended).
208 verbose exit [ -13, true ]

**Comment by dgreif** [comment]
@1092MousePad39 sorry to hear you are having issues!  I'm running homebridge on a pi as well, but I am not doing global npm installs (I have a package.json so that I can manage versions easily).  I'm really surprised that `sudo` didn't work for you, but it looks like another option is to change the install location for npm.  See https://docs.npmjs.com/getting-started/fixing-npm-permissions for instructions.

**Comment by dgreif** [comment]
@1092MousePad39 any luck getting it installed?
