### ISSUE TITLE
Should this work with Docker?

### ISSUE THREAD

**Issue by gadgetfreak98** [dgreif/homebridge-ring-alarm#13]
As an alternative, I did a docker install.  Other plugins seem to work fine, and your plugin seemed to install this way correctly. However, I cannot get anything to show up in the home app.  I know I have the right credentials.  Just logged into a new browser with the email and password that I also have in the config.json file. Thoughts?  Thanks!  Can't wait to get this to work.

Never mind!  Got it to work with a restart.  Still can't do outside of Docker, but this is great!  Thanks

**Comment by dgreif** [comment]
@gadgetfreak98 glad to hear you got it working! I'm sorry I couldn't be of more help with the npm issues.  Let me know if you run into anything odd now that you have everything up and running
