### ISSUE TITLE
Losing connection after a few hours

### ISSUE THREAD

**Issue by dgreif** [dgreif/homebridge-ring-alarm#2]
The socket.io connection with Ring gets reset after a few hours.  We receive a message with `datatype: 'HubDisconnectionEventType'`.  I've got a fix for this, but need to try it out today to be sure it works.

**Comment by dgreif** [comment]
`HubDisconnectionEventType` issue is fixed, but I'm getting occasional (once every 24-48 hours) `404` errors from the `connections` endpoint when trying to reconnect to the socket.io server.  Digging into the Ring app a little bit, it looks like there are `refresh_token`s that might be useful to keep auth tokens alive.  Need to do some more digging to see how Ring handles re-auth and what might be causing the 404 errors.

**Comment by dgreif** [comment]
Finally figured out why this is so hard to track down.  When the 404 happens, we get back an object like `{ errors: [ 7062 ] }`.  Just found the related code from Ring:

`n = t.code === c.ErrorCode.E_NOACCESS ? f.NO_ASSET : s.isNullOrUndefined(t.hasHttpErrorCode) ? f.OTHER : t.hasHttpErrorCode(7050) ? f.NO_ASSET : t.hasHttpErrorCode(7019) ? f.ASSET_OFFLINE : t.hasHttpErrorCode(7061) ? f.ASSET_CELL_BACKUP : t.hasHttpErrorCode(7062) ? f.UPDATING : t.hasHttpErrorCode(7063) ? f.MAINTENANCE : f.OTHER,`.  

`7062` corresponds with `UPDATING`, which I'm guessing means the firmware is updating.  Usually these 404's are happening at night, so a firmware update would make sense.  Need to add a retry to the `connections` endpoint for any `404` I guess.

**Comment by dgreif** [comment]
@mrose17 I was able to reproduce this issue by disconnecting my base station from the internet, which gave me a `7061` error, as I expected from the code above.  I've added a 20 second retry loop for all of the error codes listed.  Let me know if it happens for you again, but I think we've finally gotten to the bottom of this one 🎉

**Comment by mrose17** [comment]
thank you!
