### ISSUE TITLE
Status OK, but Cannot Change Alarm State from Home App

### ISSUE THREAD

**Issue by ergoego** [dgreif/homebridge-ring-alarm#3]
If I change the alarm armed state manually on the keypad, the home app will accurately display the correct state. But if I try and change state of alarm in home app, it will just stay infinitely in "disarming..." or "arming..."  Sensors also are not responsive after initial boot of Homebridge server.

**Comment by ergoego** [comment]
This issue was resolved. Due to my ring security system being on a different wifi network than the Homebridge server.

**Comment by dgreif** [comment]
@ergoego Sorry to hear you ran into some issues.  There should be no need to have the homebridge server and ring alarm on the same network, as this plugin interacts with Ring's API, not directly with the devices.  Please let me know if you are able to reproduce the issues and I will dig deeper.
