### ISSUE TITLE
Ring API unable to fetch session

### ISSUE THREAD

**Issue by dgreif** [dgreif/homebridge-ring-alarm#6]
@riveraj33 looks like I'm eating my words on the API never changing 🤦‍♂️.  Ring broke some of the old android endpoints being used by the ring-api library.  I'm updating my fork to use new endpoints and should have a fix out soon.

**Comment by riveraj33** [comment]
Hey thanks! I was wondering why I couldn’t disarm when I got home. Looking forward to the fix!

**Comment by riveraj33** [comment]
Is there a chance this was fixed on its own somehow? Everything seems to be working fine since this morning.

**Comment by dgreif** [comment]
@riveraj33 looks like Ring must have seen it as a bug and fixed it on their end.  Everything is operational again.  I may circle back in the future and change some of the endpoints being used, but everything seems to be working great as-is for now.
